spring.application.name=clouddeploy

# Server Port
server.port=8083

# File Upload
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Thymeleaf
spring.thymeleaf.cache=false

# Custom Paths
upload.dir=../uploads
extract.dir=../extracted
dockerfile.dir=../generated-dockerfiles
